version: '2'
services:
  hlvs:
    image: $HLVS_IMAGE
    # image: knarfeh/hlvs
    build:
      context: .
      dockerfile: ./Dockerfile
    # entrypoint: [python, manage.py]
    # command: [runserver, '--host', '0.0.0.0', '--port', '80']
    # entrypoint: [sh]
    volumes:
      - .:/src
      - ./container-logs:/var/log/eebook
    tty: true
    ports:
      - "$HLVS_API_PORT:80"
    env_file:
      - envs/local.env
      - envs/secret.env
    environment:
      - ENV="development"
      - no_proxy=true
      - CELERY_BROKER_URL=redis://192.168.199.121:16379/0
      - CELERY_BROKER_BACKEND=redis://192.168.199.121:16379/0
      # - SMTP_SERVER_HOST=smtp-mail.outlook.com
      - SMTP_SERVER_HOST=smtp.mailgun.org
      - SMTP_SERVER_PORT=465
      - EMAIL_FROM=eebook@eebook.org
      - EMAIL_USE_HTTP=true
    networks:
      - devbox

networks:
  devbox:
    external:
      name: devbox_devbox
