version: '2'
services:
  api:
    image: $HLVS_IMAGE
    build:
      context: .
      dockerfile: ./Dockerfile
    # entrypoint: [python, manage.py]
    # command: [runserver, '--host', '0.0.0.0', '--port', '80']
    entrypoint: [sh]
    volumes:
      - .:/src
      - ./container-logs:/var/log/eebook
    tty: true
    ports:
      - "$HLVS_API_PORT:80"
    env_file:
      - envs/local.env
      - envs/secret.env
    environment:
      - ENV="development"
    networks:
      - vlfw
  redis:
    image: "redis:alpine"
    ports:
      - '6379'
    volumes:
      - ./redis-data:/data
    networks:
      - vlfw

networks:
  vlfw:
    driver: bridge
